### ISSUE TITLE
Unable to connect AF Wire.

### ISSUE THREAD

**Issue by ghost** [AntiBlueQuirk/alternatingflux#5] opened 2018-07-12 16:26 UTC
I am unable to connect AF wire to the transformer.

AF 0.12-4
IE 0.12-83

**Comment by BrisingrAerowing** [comment] 2018-08-07 16:53
Duplicate of #3

**Comment by AntiBlueQuirk** [comment] 2018-09-01 22:04
Should be fixed by #6, new version up.

**Closed by AntiBlueQuirk** 2018-09-01 22:04 UTC
